/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webcrawlerlaste;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.JTree;

/**
 *
 * @author Irana
 */
public class DownloadPage extends javax.swing.JFrame {

    private Downloader df;
    private boolean flag = false;
    private String rootp;
    private JTree jt;

    /**
     * Creates new form DownloadPage
     */
    public DownloadPage(Downloader df , JTree jt , String rootp) {
        try {
            initComponents();
            this.setResizable(false);
            Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation((int) (d.getWidth() - this.getWidth()) / 2, (int) (d.getHeight() - this.getHeight()) / 2);
            this.setTitle(df.getFileName());
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            this.df = df;
            this.jt = jt;
            this.rootp = rootp;
            open_btn.setEnabled(false);
            url_lab.setText(df.getURL().substring(0, (df.getURL().length() > 90 ? 90 : df.getURL().length())));
            status_lab.setText((df.getStatus() ? "Downloaded" : "Not Downloaded"));
            size_lab.setText(df.getFileSize() + " Byte");
            downloaded_lab.setText("0 Byte");
            this.setAlwaysOnTop(true);
            if (df.getStatus()) {
                flag = true;
                open_btn.setEnabled(true);
                cancel_btn.setEnabled(true);
                cancel_btn.setText("Close");
                download_btn.setEnabled(false);
            }
        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, "connection problem");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        url_lab = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        download_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        status_lab = new javax.swing.JLabel();
        size_lab = new javax.swing.JLabel();
        downloaded_lab = new javax.swing.JLabel();
        open_btn = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        url_lab.setText("jLabel1");

        jLabel2.setText("Status:");

        jLabel3.setText("File Size:");

        jLabel4.setText("Downloaded:");

        download_btn.setText("Download");
        download_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                download_btnMouseClicked(evt);
            }
        });

        cancel_btn.setText("Cancel");
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
        });

        status_lab.setText("jLabel1");

        size_lab.setText("jLabel1");

        downloaded_lab.setText("jLabel1");

        open_btn.setText("Open Folder");
        open_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(url_lab)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(status_lab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(size_lab))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(downloaded_lab)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(download_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(open_btn)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(url_lab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(status_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(size_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(downloaded_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(download_btn)
                    .addComponent(cancel_btn)
                    .addComponent(open_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void download_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_download_btnMouseClicked
        // TODO add your handling code here:
        if (df.getStatus() || flag) {
            return;
        }
        df.startDownload(progressBar , this.jt , this.rootp);
        download_btn.setEnabled(false);
        cancel_btn.setEnabled(false);
        flag = true;
        new Timer().scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                downloaded_lab.setText(progressBar.getValue() + " Byte");
                if (df.getStatus()) {
                    open_btn.setEnabled(true);
                    cancel_btn.setEnabled(true);
                    cancel_btn.setText("Close");
                }
            }
        }, 0, 1000);
    }//GEN-LAST:event_download_btnMouseClicked

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        // TODO add your handling code here:
        if (cancel_btn.getText().equals("Close")) {
            this.dispose();
        } else if (flag) {
            return;
        } else {
            this.dispose();
        }


    }//GEN-LAST:event_cancel_btnMouseClicked

    private void open_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_btnMouseClicked
        try {
            // TODO add your handling code here:
            if (!df.getStatus()) {
                return;
            }
            df.openFile();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_open_btnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton download_btn;
    private javax.swing.JLabel downloaded_lab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton open_btn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel size_lab;
    private javax.swing.JLabel status_lab;
    private javax.swing.JLabel url_lab;
    // End of variables declaration//GEN-END:variables
}
